on:
  schedule:
    - cron:  '30 12 * * *'
  push:
    branches: [ main ]

name: tibber mill workflow
jobs:
  tibber-mill:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gnuplot jq imagemagick google-chrome-stable
      - name: Checkout Source Code
        uses: actions/checkout@v3
      - name: Start the Project
        run: ./run.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: allTibberMillStuff
          path: |
            /tmp/exchange/*
          if-no-files-found: error
          retention-days: 2
